version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/web/step2/SpringBoot-Test/
    overwrite: yes
    
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user